// Bakes the editable lists into the app at build time.
//
//   data/team.csv        -> src/generated/teamData.js     (the leadership cards)
//   data/expo/photos.csv -> src/generated/expoData.js     (the expo photo wall)
//
// Why not simply fetch them? Because anything served from public/ can be opened
// by anyone at a URL. Keeping the lists here — outside public/ — means they are
// still plain, editable CSV files in the project, but the only thing a visitor
// can reach is the finished page.
//
// Runs automatically before `npm start` and `npm run build` (see package.json).

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "src", "generated");

// one CSV line -> fields, honouring "quoted, values"
function parseLine(line) {
  const out = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < line.length; i += 1) {
    const c = line[i];
    if (quoted) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i += 1; }
      else if (c === '"') quoted = false;
      else cur += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") { out.push(cur.trim()); cur = ""; }
    else cur += c;
  }
  out.push(cur.trim());
  return out;
}

function readCsv(relPath) {
  const file = path.join(ROOT, relPath);
  if (!fs.existsSync(file)) {
    console.warn(`  ! ${relPath} not found — nothing generated`);
    return [];
  }
  const lines = fs.readFileSync(file, "utf8").split(/\r?\n/).filter((l) => l.trim() && !l.trim().startsWith("#"));
  const rows = lines.slice(1).map(parseLine);
  console.log(`  ${relPath}: ${rows.length} row(s)`);
  return rows;
}

function write(relOut, banner, name, rows) {
  const body = `// GENERATED by scripts/build-data.js from ${banner} — do not edit here.
// Edit that CSV instead; this file is rewritten on every start and build.
export const ${name} = ${JSON.stringify(rows, null, 2)};
`;
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, relOut), body, "utf8");
}

console.log("baking the editable lists into the app:");

// leadership: name, role, photo, avatar, bio
const team = readCsv("data/team.csv").map(([name, role, photo, avatar, bio]) => ({
  name: (name || "").trim(),
  role: (role || "").trim(),
  photo: (photo || "").trim() || null,
  avatar: (avatar || "").trim() || null,
  bio: (bio || "").trim(),
})).filter((t) => t.name);
write("teamData.js", "data/team.csv", "TEAM_ROWS", team);

// expo photographs: folder, file, year, event, caption, link, video, clip
const expo = readCsv("data/expo/photos.csv").map(([folder, file, year, event, caption, link, video, clip]) => ({
  folder: (folder || "").trim(),
  file: (file || "").trim(),
  year: (year || "").trim(),
  event: (event || "").trim(),
  caption: (caption || "").trim(),
  link: /^https?:\/\//i.test((link || "").trim()) ? link.trim() : "",
  video: /^https?:\/\//i.test((video || "").trim()) ? video.trim() : "",
  clip: (clip || "").split("|")[0].trim(),
  clipLabel: ((clip || "").split("|")[1] || "").trim() || "Expo clip",
})).filter((r) => r.file);
write("expoData.js", "data/expo/photos.csv", "EXPO_ROWS", expo);

// services: name, text, image
const services = readCsv("data/services.csv").map(([name, text, image]) => ({
  name: (name || "").trim(),
  text: (text || "").trim(),
  img: (image || "").trim(),
})).filter((s) => s.name);
write("servicesData.js", "data/services.csv", "SERVICE_ROWS", services);

console.log("done.");
